p8105_hw1_yd2739
================
Yuxuan Du
2023-09-14

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Problem 1

``` r
library("moderndive")
data("early_january_weather")
variables = colnames(early_january_weather)
observation_num = nrow(early_january_weather)
variable_num = ncol(early_january_weather)
mean_temp = mean(early_january_weather$temp)
q1_scatter = ggplot(data = early_january_weather, 
       mapping = aes(x = time_hour, 
                y = temp, 
                color = humid)) + 
  geom_point()
ggsave(
  'problem_1_scatter.png',
  plot = q1_scatter,
  device = png
)
```

    ## Saving 7 x 5 in image

``` r
q1_scatter
```

![](p8105_hw1_yd2739_files/figure-gfm/unnamed-chunk-2-1.png)<!-- --> the
variables in the dataset are: origin, year, month, day, hour, temp,
dewp, humid, wind_dir, wind_speed, wind_gust, precip, pressure, visib,
time_hour.

the size of the data is 358 x 15.

the mean temperature is 39.5821229 degree.

## Problem 2

``` r
Q2_df = tibble(
  samp_10_norm = rnorm(10),
  samp_10_norm_logic = samp_10_norm > 0,
  samp_char_vec = c('A', 'B', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K'),
  samp_fac_vec = factor(c(-1, -1, 0, 0, 0, 0, 1, 1, 1, -1))
)
Q2_df
```

    ## # A tibble: 10 × 4
    ##    samp_10_norm samp_10_norm_logic samp_char_vec samp_fac_vec
    ##           <dbl> <lgl>              <chr>         <fct>       
    ##  1      -0.652  FALSE              A             -1          
    ##  2       0.0102 TRUE               B             -1          
    ##  3       0.0589 TRUE               D             0           
    ##  4      -0.197  FALSE              E             0           
    ##  5       0.712  TRUE               F             0           
    ##  6      -0.173  FALSE              G             0           
    ##  7       0.0707 TRUE               H             1           
    ##  8      -0.261  FALSE              I             1           
    ##  9       0.307  TRUE               J             1           
    ## 10       0.726  TRUE               K             -1

``` r
mean(pull(Q2_df, samp_10_norm))
```

    ## [1] 0.06001974

``` r
mean(pull(Q2_df, samp_10_norm_logic))
```

    ## [1] 0.6

``` r
mean(pull(Q2_df, samp_char_vec))
```

    ## Warning in mean.default(pull(Q2_df, samp_char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(Q2_df, samp_fac_vec))
```

    ## Warning in mean.default(pull(Q2_df, samp_fac_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

among the four vector, char vector and factor vector cannot take mean

``` r
as.numeric(pull(Q2_df, samp_10_norm_logic))
as.numeric(pull(Q2_df, samp_char_vec))
as.numeric(pull(Q2_df, samp_fac_vec))
```

We could calculate the mean and transform to numeric for logic vector.
But for char vector, it says NAs introduced by coercion when executing,
and it cannot be transformed to numeric vector. So it is reasonable that
we cannot calculate the mean of char vector. But for factor vector, the
transformation to numeric form seems successes. So it is still not sure
why we cannot calculate the mean of the factor vector
